# For more information, see:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: Windows
  pool:
    name: HomeSystem
    demands:
    - cmake

  steps:
  - task: CMake@1
    displayName: 'CMake --build . --config Release'
    inputs:
      cmakeArgs: '--build .\build -S . --config Release'

  - task: CMake@1
    displayName: 'CMake -E chdir .\build cpack -C Debug -G 7Z'
    inputs:
      cmakeArgs: '-E chdir .\build cpack -C Debug -G 7Z'

  - task: CopyFiles@2
    displayName: 'Copy CPack Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: 'build\_CPack_Packages\win32\7Z\'
      Contents: '*.7z'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'